//! Embedded key-value store backing favorites, tag overrides, tag catalog,
//! rating overrides, and picker state. Replaces the five separate JSON
//! files those types used to maintain.
//!
//! Indexes stay as JSON files since they're regenerated by every
//! `wallrack index` run and bypassing JSON would just trade one binary
//! format for another; the win there is small.
//!
//! Sled trees in use:
//!
//! - `favorites`         — key `<integration>\0<id>`, value: empty marker
//! - `tag_overrides`     — key `<integration>\0<id>`, value: JSON `EntryOverride`
//! - `tag_catalog`       — key `<integration>\0<tag>`, value: empty marker
//! - `rating_overrides`  — key `<integration>\0<id>`, value: rating string
//! - `state`             — key picker-state key, value: state string

use std::path::Path;

use anyhow::{Context, Result};
use serde::Serialize;
use serde::de::DeserializeOwned;
use sled::{Db, Tree};

mod migrate;

pub const TREE_FAVORITES: &str = "favorites";
pub const TREE_TAG_OVERRIDES: &str = "tag_overrides";
pub const TREE_TAG_CATALOG: &str = "tag_catalog";
pub const TREE_RATING_OVERRIDES: &str = "rating_overrides";
pub const TREE_STATE: &str = "state";

/// Composite key separator. NUL keeps the two halves unambiguous since
/// neither integration keys nor entry ids contain NUL.
pub const KEY_SEP: u8 = 0;

/// Build a sled key from `<integration>\0<rest>`.
pub fn composite_key(integration: &str, rest: &str) -> Vec<u8> {
    let mut k = Vec::with_capacity(integration.len() + 1 + rest.len());
    k.extend_from_slice(integration.as_bytes());
    k.push(KEY_SEP);
    k.extend_from_slice(rest.as_bytes());
    k
}

/// Split a composite key back into `(integration, rest)`. Returns `None` if
/// the key isn't UTF-8 or doesn't contain the separator.
pub fn split_composite(key: &[u8]) -> Option<(&str, &str)> {
    let s = std::str::from_utf8(key).ok()?;
    s.split_once(char::from(KEY_SEP as char))
}

/// Open the sled database at `cache_root/db` and run the one-shot migration
/// from any legacy JSON files still on disk. Idempotent — running it on an
/// already-migrated cache is a no-op.
pub fn open(cache_root: &Path) -> Result<Db> {
    let db_path = cache_root.join("db");
    let db = sled::Config::new()
        .path(&db_path)
        // Reasonable defaults: ~4MB cache is plenty for our key space.
        .cache_capacity(4 * 1024 * 1024)
        .open()
        .with_context(|| format!("open sled db at {}", db_path.display()))?;
    migrate::run(cache_root, &db)?;
    Ok(db)
}

/// Read a serde-deserializable value from `tree` under `key`. Returns
/// `Ok(None)` if the key is absent.
pub fn read_json<T: DeserializeOwned>(tree: &Tree, key: &[u8]) -> Result<Option<T>> {
    let Some(bytes) = tree.get(key)? else { return Ok(None) };
    let parsed = serde_json::from_slice(&bytes)
        .with_context(|| format!("decode value for key {:?}", String::from_utf8_lossy(key)))?;
    Ok(Some(parsed))
}

/// Write a serde-serializable value to `tree` under `key`.
pub fn write_json<T: Serialize>(tree: &Tree, key: &[u8], value: &T) -> Result<()> {
    let bytes = serde_json::to_vec(value).context("serialize value for sled tree")?;
    tree.insert(key, bytes)?;
    Ok(())
}
