//! Embedded key-value store backing favorites, tag overrides, tag catalog,
//! rating overrides, and picker state. Replaces the five separate JSON
//! files those types used to maintain.
//!
//! Indexes stay as JSON files since they're regenerated by every
//! `wallrack index` run and bypassing JSON would just trade one binary
//! format for another; the win there is small.
//!
//! Sled trees in use:
//!
//! - `favorites`         — key `<integration>\0<id>`, value: empty marker
//! - `tag_overrides`     — key `<integration>\0<id>`, value: JSON `EntryOverride`
//! - `tag_catalog`       — key `<integration>\0<tag>`, value: empty marker
//! - `rating_overrides`  — key `<integration>\0<id>`, value: rating string
//! - `state`             — key picker-state key, value: state string

use std::io;
use std::path::Path;
use std::thread;
use std::time::{Duration, Instant};

use anyhow::{Context, Result};
use serde::Serialize;
use serde::de::DeserializeOwned;
use sled::{Db, Tree};

mod migrate;

pub const TREE_FAVORITES: &str = "favorites";
pub const TREE_TAG_OVERRIDES: &str = "tag_overrides";
pub const TREE_TAG_CATALOG: &str = "tag_catalog";
pub const TREE_RATING_OVERRIDES: &str = "rating_overrides";
pub const TREE_STATE: &str = "state";
pub const TREE_APPLIED: &str = "applied";

/// Composite key separator. NUL keeps the two halves unambiguous since
/// neither integration keys nor entry ids contain NUL.
pub const KEY_SEP: u8 = 0;

/// Build a sled key from `<integration>\0<rest>`.
pub fn composite_key(integration: &str, rest: &str) -> Vec<u8> {
    let mut k = Vec::with_capacity(integration.len() + 1 + rest.len());
    k.extend_from_slice(integration.as_bytes());
    k.push(KEY_SEP);
    k.extend_from_slice(rest.as_bytes());
    k
}

/// Split a composite key back into `(integration, rest)`. Returns `None` if
/// the key isn't UTF-8 or doesn't contain the separator.
pub fn split_composite(key: &[u8]) -> Option<(&str, &str)> {
    let s = std::str::from_utf8(key).ok()?;
    s.split_once(KEY_SEP as char)
}

/// Open the sled database at `cache_root/db` and run the one-shot migration
/// from any legacy JSON files still on disk. Idempotent — running it on an
/// already-migrated cache is a no-op.
///
/// Sled grabs an exclusive flock for the lifetime of the process, so two
/// `wallrack` invocations running at once (e.g. the rofi script firing
/// `wallrack view` while a background `wallrack index` is still running)
/// would otherwise fail instantly with `WouldBlock`. Retry briefly so they
/// serialize instead.
pub fn open(cache_root: &Path) -> Result<Db> {
    let db_path = cache_root.join("db");
    let cfg = sled::Config::new()
        .path(&db_path)
        // Reasonable defaults: ~4MB cache is plenty for our key space.
        .cache_capacity(4 * 1024 * 1024);

    let deadline = Instant::now() + Duration::from_secs(10);
    let mut backoff = Duration::from_millis(50);
    let db = loop {
        match cfg.open() {
            Ok(db) => break db,
            Err(sled::Error::Io(ref e))
                if e.kind() == io::ErrorKind::WouldBlock && Instant::now() < deadline =>
            {
                thread::sleep(backoff);
                backoff = (backoff * 2).min(Duration::from_millis(500));
                continue;
            }
            Err(e) => {
                return Err(anyhow::Error::new(e))
                    .with_context(|| format!("open sled db at {}", db_path.display()));
            }
        }
    };
    migrate::run(cache_root, &db)?;
    Ok(db)
}

/// Read a serde-deserializable value from `tree` under `key`. Returns
/// `Ok(None)` if the key is absent.
pub fn read_json<T: DeserializeOwned>(tree: &Tree, key: &[u8]) -> Result<Option<T>> {
    let Some(bytes) = tree.get(key)? else {
        return Ok(None);
    };
    let parsed = serde_json::from_slice(&bytes)
        .with_context(|| format!("decode value for key {:?}", String::from_utf8_lossy(key)))?;
    Ok(Some(parsed))
}

/// Write a serde-serializable value to `tree` under `key`.
pub fn write_json<T: Serialize>(tree: &Tree, key: &[u8], value: &T) -> Result<()> {
    let bytes = serde_json::to_vec(value).context("serialize value for sled tree")?;
    tree.insert(key, bytes)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn composite_key_uses_nul_separator() {
        let k = composite_key("booru", "konachan:42");
        assert_eq!(k, b"booru\0konachan:42");
    }

    #[test]
    fn composite_key_handles_empty_components() {
        assert_eq!(composite_key("", "id"), b"\0id");
        assert_eq!(composite_key("integration", ""), b"integration\0");
    }

    #[test]
    fn split_composite_recovers_both_halves() {
        let key = composite_key("we", "456");
        assert_eq!(split_composite(&key), Some(("we", "456")));
    }

    #[test]
    fn split_composite_returns_none_for_invalid_input() {
        // No separator.
        assert_eq!(split_composite(b"nosep"), None);
        // Invalid UTF-8.
        assert_eq!(split_composite(&[0xff, 0x00, b'x']), None);
    }

    #[test]
    fn split_composite_stops_at_first_separator() {
        // A rest containing NUL should still split on the first NUL only,
        // so the integration half stays a clean string.
        let k = composite_key("wp", "a\0b");
        let (i, rest) = split_composite(&k).unwrap();
        assert_eq!(i, "wp");
        assert_eq!(rest, "a\0b");
    }
}
